name: Trivy Scan with SBOM

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Trivy scan with SBOM output
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs           # scan filesystem
          input: '.'              # scan current directory
          format: cyclonedx       # generate CycloneDX SBOM
          output: trivy-report.json
          scanners: vuln          # enable vulnerability scanning explicitly
          severity: CRITICAL,HIGH,MEDIUM
 
