name: Trivy Scan with SBOM

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy SBOM generation and vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs               # filesystem scan
          input: ./project-src        # path to scan, adjust to your code location
          format: cyclonedx           # output SBOM in cyclonedx format
          output: trivy-report.json   # output file
          ignore-unfixed: true        # ignore unfixed vulnerabilities
          vuln-type: os,library       # scan for OS and library vulnerabilities
          severity: CRITICAL,HIGH,MEDIUM
          scanners: vuln,license      # explicitly enable vulnerability and license scanners
