name: SBOM Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # if you have dependencies for your script

    - name: Merge SBOMs
      run: |
        python merge_sbom.py project-src/merged-sbom.json project-src/sbom1.json project-src/sbom2.json
      # Adjust the paths and script name as needed

    - name: Validate merged SBOM JSON
      run: |
        python -c "import json; json.load(open('project-src/merged-sbom.json'))"

    - name: Run Trivy scan on merged SBOM
      run: |
        docker run --rm -v ${{ github.workspace }}/project-src:/project aquasec/trivy:latest sbom /project/merged-sbom.json
