name: Scan Other Repo with Trivy

on:
  workflow_dispatch: # Manual trigger for easy testing

jobs:
  trivy-scan-other-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo (optional)
        uses: actions/checkout@v3

      - name: Checkout other repository
        uses: actions/checkout@v3
        with:
          repository: username/other-repo   # <-- Change this!
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: other-repo-folder

      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v2

      - name: Run Trivy scan on other repo
        run: |
          trivy fs ./other-repo-folder --format sarif -o trivy-results.sarif

      - name: Upload Trivy results artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results-other-repo
          path: trivy-results.sarif
