name: Conan + Trivy Full SBOM Scan

on:
  workflow_dispatch:
    inputs:
      src_repository:
        description: 'Source Repository (e.g., user/repo)'
        required: true
      src_branch:
        description: 'Branch of source repository'
        required: false
        default: 'main'
      conan_repository:
        description: 'Repository containing conanfile.py'
        required: true
      conan_branch:
        description: 'Branch for Conan repository'
        required: false
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      # -----------------------------
      # SETUP
      # -----------------------------
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # -----------------------------
      # CHECKOUT REPOSITORIES
      # -----------------------------
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.src_repository }}
          ref: ${{ inputs.src_branch }}
          path: project-src

      - name: Checkout Conan repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.conan_repository }}
          ref: ${{ inputs.conan_branch }}
          path: conan-src

      # -----------------------------
      # INSTALL DEPENDENCIES
      # -----------------------------
      - name: Install Conan and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install conan
          conan profile detect --force

      - name: Generate Conan lockfile
        run: |
          conan lock create conanfile.py --lockfile-out=conan.lock
        working-directory: conan-src

      - name: Copy Conan lockfile
        run: cp conan-src/conan.lock project-src/conan.lock

      # -----------------------------
      # TRIVY SCAN BOTH REPOS (SBOM)
      # -----------------------------
      - name: Run Trivy scan on source repo
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          input: './project-src'
          format: cyclonedx
          scanners: vuln
          output: project-src/trivy-src.json
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH,MEDIUM

      - name: Run Trivy scan on Conan repo
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          input: './conan-src'
          format: cyclonedx
          scanners: vuln
          output: conan-src/trivy-conan.json
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH,MEDIUM

      # -----------------------------
      # MERGE BOTH SBOMS
      # -----------------------------
      - name: Merge Trivy SBOMs
        run: |
          cat > merge_s_
